[Output_None]
<fusedoc fuse="dsp_Footer.lasso" language="Lasso" specification="3.0">
	<responsibilities>I am the footer file.</responsibilities>
	<properties>
		<history author="Rich Tretola" date="10/10/2002" email="rich@lassofusebox.org" role="Architect" type="Create"/>
		<history author="Tami Williams" date="5/1/2008" email="tami@asktami.com" type="Update" />
	</properties>
</fusedoc>
[/Output_None]


<table width="100%" cellspacing="0" cellpadding="0">
	<tr>
		<td class="bodycopy" align="center">
		<a href="http://www.lassofusebox.org" target="_blank">www.lassofusebox.org</a>&nbsp;&nbsp;
		</td>
	</tr>
 </table>