<?LassoScript
/*
<fusedoc fuse="fbx_CustomTags.inc" language="Lasso" specification="3.0">
	<responsibilities>
		I hold the user defined custom tags used within the application. There should be only one fbx_CustomTags.inc file within the application and it should reside within the root folder.
	</responsibilities>	
	<properties>
		<history author="Tami Williams" date="May 2003" email="tami@asktami.com" type="Create" />
	</properties>
</fusedoc>
*/


?>