<?LassoScript
Output_None;
/*
<fusedoc fuse="dsp_thankyou.inc" language="Lasso" specification="3.0">
	<responsibilities>I display a thanyou page.</responsibilities>
	<properties>
		<history author="Rich Tretola" date="02/06/2003" email="rich@lassofusebox.org" role="Architect" type="Create"/>
		<history author="Tami Williams" date="05/23/06" email="tami@asktami.com" type="Update" />
	</properties>
</fusedoc>
*/
/Output_None;
?>

<table align="center">
	<tr>
		<td class="bodycopy">Check your email box.</td>
	</tr>
</table>