<html>
<FRAMESET rows="150,*" frameborder="1" border="1" marginwidth="0" marginheight="0"  scrolling="no" noresize>
<FRAME NAME="header" SRC="[$selfFrameSet]frmheader">
     <FRAMESET cols="200, *" frameborder="1" border="1" marginwidth="0" marginheight="0"  scrolling="no" noresize>
			<FRAME NAME="menu" SRC="[$selfFrameSet]frmmenu">
			<FRAME NAME="content" SRC="[$selfFrameSet]main" scrolling="yes">
     </FRAMESET>
     
<noframes>
  <body>
  <p>&nbsp;</p>   
  <p>&nbsp;</p>   
  <p>&nbsp;</p>    
        <center>    
<h3>This site is designed to be viewed by a browser which supports
Netscape's frames extension.</h3>
  <p>&nbsp;</p>    
  <p>&nbsp;</p>   
<b>Please download <a href="http://home.netscape.com/computing/download/index.html">Netscape Communicator</a> or <a href="http://www.microsoft.com/windows/ie/default.htm">Microsoft Internet Explorer</a>.</b>
  <p>&nbsp;</p>    
  <p>&nbsp;</p>     
&copy; 1999-2002 Tami Williams, Creative Computing. All rights reserved. | 
Comments should be sent to <a href="mailto:info@asktami.com?subject=Saw Your Web Site">info@asktami.com</a>. 
  </center>
        </body> 
  </noframes>
</FRAMESET>
</html>