[
/*
<fusedoc fuse="dsp_secured.inc" language="Lasso" specification="3.0">
<responsibilities>I am the Secure circuit home page.</responsibilities>
<properties>
 <history author="Tami Williams" date="June 2008" email="tami@asktami.com" type="Create" />
 <history author="Tami Williams" date="4/28/2012" email="tami@asktami.com" type="Update" />
</properties>
<io>
 <in>
	 <number name="lid" format="LDML" Scope="variables"/>
 </in>
</io>
</fusedoc>
*/
]

<h3>You're logged in, so you get to see this page!</h3>
