[
/*
<fusedoc fuse="dsp_logout.inc" language="Lasso" specification="3.0">
<responsibilities>I am the logout page.</responsibilities>
<properties>
 <history author="Tami Williams" date="June 2008" email="tami@asktami.com" type="Create" />
 <history author="Tami Williams" date="4/28/2012" email="tami@asktami.com" type="Update" />
</properties>
<io>
 <in>
	 <String name="[$XFA_welcome]" format="LDML" Scope="variables"/>
 </in>
</io>
</fusedoc>
*/
]



Thank you. You have successfully logged out.
<br><br>
For maximum security, we recommend that all users<br>close their browser window immediately after logging out.
<p>&nbsp;</p>
<a href="[$XFA_welcome]">Click here</a> to return to the home page.
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>