[
/*
<fusedoc fuse="dsp_cookietest.inc" language="Lasso" specification="3.0">
<responsibilities>I am the page the users see if either cookies or javascript are turned off.</responsibilities>
<properties>
 <history author="Tami Williams" date="June 2008" email="tami@asktami.com" type="Create" />
 <history author="Tami Williams" date="4/28/2012" email="tami@asktami.com" type="Update" />
</properties>
<io>
 <in>
	 <String name="[$XFA_welcome]" format="LDML" Scope="variables"/>
 </in>
</io>
</fusedoc>
*/
]

<p><b>Cookies and/or javascript are turned off</b></p>

<p>This site utilizes cookie and javascript technology from within your web browser to authenticate you to the system.
</p>
<p>All a cookie is a small bit of data that is stored with your web browser after you log-in so that every time you make a request from the web site we can check to make sure you are authorized to make that request for information. When you quit your browser the cookies are removed from your PC. 
</p>
<p>Imagine a cookie as a key you use to open all of the doors to the data you wish to find out about.
</p>
<p>In order to use this site you need to make sure that you meet the following technical criteria:<br>
<ul type="circle">
	<li>Your web browser must support the use of cookies and javascript.
	<li>Cookies and javascript must be turned on in your web browser.
</ul>
</p>
<p>Cookies and javascript are supported in almost every web browser, including Internet Explorer and Netscape browsers. <b>And, by default, most web browsers are already pre-configured to use both cookies and javascript.</b>
</p>
<p><b>As a result, chances are that you are already set up to use cookies and javascript.</b> However, if cookies and javascript are turned off in your web browser, please consult your web browser's documentation or help system for how to turn them on again. Usually, it only involves going into the web browser's settings and clicking a box to activate them.
</p>
<p><b>After you have turned on both cookies and javascript, <a href="[$XFA_welcome]">click here</a>.</b>
</p>