[
/*
<fusedoc fuse="fbx_Sessions.inc" language="Lasso" specification="3.0">
	<responsibilities>
		I define any sessions needed within the application. There should be only one fbx_Sessions.inc file within the application and it should reside within the root folder.
	</responsibilities>	
   <properties>
	   <history author="Tami Williams" date="May 2003" email="tami@asktami.com" type="Update">
		 From www.listsearch.com/ ID= 105874  
		 If action params are set to variables before [session_start] on the page then any existing session variable will overwrite user-injected variables. Action_Params/Client_PostArgs are set to variables inside the fusebox file prior to starting the session.
	   </history>
	   <history author="Tami Williams" date="4/20/2012" email="tami@asktami.com" type="Update" />
   </properties>
</fusedoc>
*/

]