[
/*
<fusedoc fuse="vl_Title.inc" language="Lasso" specification="3.0">
<responsibilities>I am the valuelist for the TITLE field.</responsibilities>	
<properties>
	<history author="Tami Williams" date="May 2008" email="tami@asktami.com" type="Create" />
	<history author="Tami Williams" date="4/5/2012" email="tami@asktami.com" type="Update" />
</properties>
<io>
 <out>
	 <string name="vl_Title" scope="variables" />
 </out>
</io>
</fusedoc>
*/

		var(
		'vl_Title' = Array('Mr.', 'Mrs.', 'Ms.', 'Dr.')
		);

]