[
/*
<fusedoc fuse="dsp_popup.inc" language="Lasso" specification="3.0">
<responsibilities>I am the Popup circuit example page.</responsibilities>
<properties>
 <history author="Tami Williams" date="June 2008" email="tami@asktami.com" type="Create" />
 <history author="Tami Williams" date="4/28/2012" email="tami@asktami.com" type="Update" />
</properties>
</fusedoc>
*/
]


EXAMPLE POPUP
<br>
- this is the pop_example.inc in the popups circuit