<a href=" [if:$frame=='Y'][$selfFrameY][else][$selfFrameN][/if]" TARGET="_top"><strong>Family:</strong></a><br>
<img src="[$currentpath][$img]grandpa.gif"><a href="[$XFA_Grandpa]" [if:$frame=='Y'][$targetContent][/if]>Grandpa</a><br>
&nbsp;&nbsp;&nbsp;<img src="[$currentpath][$img]homer.gif"><a href="[$XFA_Homer]" [if:$frame=='Y'][$targetContent][/if]>Homer</a><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="[$currentpath][$img]Bart.gif"><a href="[$XFA_Bart]" [if:$frame=='Y'][$targetContent][/if]>Bart</a><br>
&nbsp;&nbsp;&nbsp;<img src="[$currentpath][$img]Marge.gif"><a href="[$XFA_Marge]" [if:$frame=='Y'][$targetContent][/if]>Marge</a><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="[$currentpath][$img]Lisa.gif"><a href="[$XFA_Lisa]" [if:$frame=='Y'][$targetContent][/if]>Lisa</a><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="[$currentpath][$img]Maggie.gif"><a href="[$XFA_Maggie]" [if:$frame=='Y'][$targetContent][/if]>Maggie</a><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="[$currentpath][$img]Maggie.gif"><a href="[$XFA_MaggieALT]" [if:$frame=='Y'][$targetContent][/if]>Maggie NotNested</a><br>