<?LassoScript
/*
<fusedoc fuse="fbx_Circuits.inc" language="Lasso" specification="3.0">
	<responsibilities>
		I define the Circuits structure used with Fusebox 3.0
	</responsibilities>	
	<properties>
		<history author="Tami Williams" date="May 2008" email="tami@asktami.com" type="Update" />
	</properties>
	<io>
		<out>
			<string name="fusebox.circuits.*" comments="set a variable for each circuit name" />
		</out>
	</io>
</fusedoc>
*/

$_Circuits->(Insert:'ContactApp'='ContactApp');
?>