[
/*
<fusedoc fuse="dsp_Header.lasso" language="Lasso" specification="3.0">
	<responsibilities>I am the header file.</responsibilities>
	<properties>
		<history author="Rich Tretola" date="10/10/2002" email="rich@lassofusebox.org" role="Architect" type="Create" />
		<history author="Tami Williams" date="5/1/2008" email="tami@asktami.com" type="Update" />
		<history author="Tami Williams" date="4/5/2012" email="tami@asktami.com" type="Update" />
	</properties>
</fusedoc>
*/
]

<table width="100%" cellspacing="0" cellpadding="0">
	<tr>
		<td class="Headline" align="center">Lasso Fusebox Sample ContactApp</td>
	</tr>
	<tr>
		<td align="center">lasso_version = [lasso_version]
		<br>gServerName  = [$gServerName]
		<br>appLocation  = [$appLocation]
		</td>
	</tr>
 </table>