    <CENTER>
       <A HREF="[$XFA_help]" [$targetString]>Help</A>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp; 
       <A HREF="[$XFA_credits]" [$targetString]>Credits</A>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp; 
       <A HREF="[$XFA_contact_me]" [$targetString]>Contact me</A>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;
       <A HREF="?frame=Y" TARGET="_top">Frames</A>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<A HREF="?frame=N" TARGET="_top">No&nbsp;Frames</A>
       </CENTER>